config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get "/welcome", to: "home#index"

  get '/users/my_topics', to: 'users#my_topics', as: "my_topics"
  get '/users/my_categories', to: 'users#my_categories', as: "my_categories"
  get '/users/my_schedules', to: 'users#my_schedules', as: "my_schedules"
  
  resources :categories

  resources :topics

  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categories_topic.rb
class CategoriesTopic < ApplicationRecord
  belongs_to :topic, optional: true
  belongs_to :category, optional: true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :categories_topics
  has_many :topics, through: :categories_topics, dependent: :destroy
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  has_rich_text :note
  belongs_to :user

  def self.search(term)
    self.where("lower(event) LIKE lower(?)", "%#{term}%")
  end 
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_rich_text :note
  belongs_to :user 
  has_many :categories_topics
  has_many :categories, through: :categories_topics, dependent: :destroy

  def self.search(term)
    self.where("lower(name) LIKE lower(?)", "%#{term}%")
  end 

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :topics
  has_many :categories
  has_many :schedules
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  #before_action :authenticate_user!
  before_action :authenticate_user!, except: [:index]
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy ]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def new
    
    @category = Category.new
  end

  def create
    
    @category = current_user.categories.create(category_params) 
    if @category.save
      redirect_to @category
    else
      render "new"
    end
  end

  def index
    @topics = Topic.all
    @categories = Category.all
  end

  
  def show
    @topics = Topic.all
  end

  def edit
   
  end

  def update
   
    if @category.update(category_params)
      redirect_to @category
    else
      render "edit"
    end
  end

  
  def destroy
    @category.destroy
    redirect_to my_categories_path
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :color, :topic_id)
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    
  end

  def welcome
  end
  
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  
  def index
    @schedules = Schedule.all
  end

  def show
  end

  def new
    @schedule = Schedule.new
  end

  def edit
  end

  def create
    @schedule = current_user.schedules.create(schedule_params)
    if @schedule.save
      redirect_to @schedule, {notice: "Schedule was successfully created." }
    else
      render "new"
    end
  end

  def update
    if @schedule.update(schedule_params)
      redirect_to @schedule
    else
      render "edit"
    end
  end

  def destroy
    @schedule.destroy
    redirect_to my_schedules_path
  end

  private
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    def schedule_params
      params.require(:schedule).permit(:date, :event, :note)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def new
    
    @topic = Topic.new 
    @categories = Category.all
    
  end

  def create
    
    @categories = Category.all
    @topic = current_user.topics.create(topic_params)
    if @topic.save
      redirect_to @topic
    else
      render "new"
    end
  end

  def index
  end

  def show
    
  end

  def edit
    @categories = Category.all
  end

  def update
    if @topic.update(topic_params)
      redirect_to @topic
    else
      render "edit"
    end
  end

  def destroy 
    @topic.destroy
    redirect_to my_topics_path
  end
  

  private
    def set_topic
      @topic = Topic.find(params[:id])
    end
    
    def topic_params
      params.require(:topic).permit(:name, :description, :link, :note, category_ids:[])
    end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]
    before_action :configure_account_update_params, only: [:update]

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end

    # If you have extra params to permit, append them to the sanitizer.
    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end

    private

    def sign_up_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_topics
    @categories = Category.all
    @categories = current_user.categories
    @topics = current_user.topics
    @pagy, @topics = pagy(current_user.topics.order("created_at DESC"), items: 10)
    if params[:topic_name]
      @pagy, @topics = pagy(@topics.search(params[:topic_name]), items: 10) 
    end

  end

  def my_categories
    @pagy, @categories = pagy(current_user.categories, items: 8) 

  end

  def my_schedules
    @schedules = current_user.schedules
    #@pagy, @schedules = pagy(current_user.schedules.order("created_at DESC"), items: 8)
    if params[:schedule_event]
      @pagy, @schedules = pagy(@schedules.search(params[:schedule_event]), items: 10) 
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/categories/_form.html.erb
<section class="section-form">
  <div id="card-border" class="card card-form">
    <div class="card-body">
      <%= form_with(model: category) do |f| %>
        <% if category.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
            <ul>
              <% category.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="row">
          <div class=" col-md-11 form-group">
            <%= f.label :name %>
            <%= f.text_field :name,class: 'form-control' %>
          </div>

          <div class="col-md-1 form-group">
            <%= f.label :color %>
            <%= f.color_field :color,class: 'form-control'%>
          </div>
        </div>
        <div class="actions">
          <%= f.submit "Guardar", class:"btn btn-sm btn-success mt-3" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/categories/edit.html.erb
<h1>Editar categoría</h1>
<%= render 'form', category: @category %>
<%= link_to 'Atras', @category, class: "btn btn-primary mt-2" %>

app/views/categories/new.html.erb
<h1 class="title">Crear Categoría</h1>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<h1 class= "title">Categoría</h1>
<div class="row">
  <div class="col-sm-12">
    <div id="card-border" class="card">
      <div class="card-body">
        <h5 class="card-title text-white p-3" style="background-color: <%= @category.color%>" >Categoría: <%= @category.name %></h5>
        <hr>
        <div class="panel-body well" >
            <h5 class="card-title p-3">Recursos</h5>
            <ul>
              <% @category.topics.each do |topic|%>
                <li><%= topic.name %></li>
              <% end %>
            </ul>
          </div>
      </div>
    </div>
    <div class="mt-3 content-btns">
      <%= link_to 'Atras', my_categories_path, class: 'btn btn-primary text-white btns' %>
      <%= link_to 'Editar', edit_category_path(@category), class: 'btn btn-warning text-white btns' %>
      <%= link_to "Eliminar", @category, method: :delete, class: 'btn btn-danger text-white btns' %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<section class="section-welcome">
  <body class="welcome">
    <div id="portada-movil">
      <header>
        <p style="text-align: center">
          <img src="/cover-sm.png" class="img-movil" alt="Portada Guis virtual" width="320" height="auto" />
        </p>
      </header>     
      <div class="col-xl-9 col-lg-10 mx-auto">
        <div class="bg-faded rounded p-3 ">
          <div class="">
            <% if user_signed_in? %>
              <h1 class="display-5">Hola <%= current_user.name %>!</h1>
              <p class="lead">Bienvenido a tus recursos online, 
                              espero sea de gran ayuda, y pongas en practica esos conocimientos. <br> <span style="font-weight: bold;"> Úsalo con responsabilidad</span></p>
            <% else %>
              <h1 class="display-5">Hola, que tal!</h1>
              <p class="lead">Este es un espacio, para ayudarte a organizar tus recursos de aprendizaje o laborales online, 
                              espero te sea de gran ayuda. <br> <span style="font-weight: bold;"> Úsalo con responsabilidad</span></p>
              <hr class="my-2">
            <% end%>
            <h2 class="section-heading mb-4">
              <span class="section-heading-lower">Guia Virtual |</span>
              <span class="section-heading-upper">Aprende &amp; Practica</span>
            </h2>
            <% if user_signed_in? %>
              <p class="lead">
                <%= link_to " Recursos", my_topics_path, class:"btn btn-sm btn-success"%>
              </p>
            <% else %>
              <p class="lead">
                <%= link_to "Iniciar Sesión",  new_user_session_path, class:"btn btn-sm btn-success"%>
              </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <section id="no-info-home" class="page-section about-heading">
      <div class="container">
        <div class="about-heading-content">
          <div class="row test">
            <div class="col-xl-9 col-lg-10 mx-auto ">
              <div class="bg-faded rounded p-3 ">
                <div class="">
                  <% if user_signed_in? %>
                    <h1 class="display-5 user-active">Hola <%= current_user.name %>!</h1>
                    <p class="lead">Bienvenido a tu espacio de aprendizaje online, 
                                    espero aprendas mucho, y pongas en practica esos conocimientos. <br> <span style="font-weight: bold;"> Úsalo con responsabilidad</span></p>
                  <% else %>
                    <h1 class="display-5">Hola, que tal!</h1>
                    <p class="lead">Este es un espacio, para ayudar a organizar tus recursos de aprendizaje online, 
                                    espero aprendas mucho, y pongas en practica esos conocimientos. <br> <span style="font-weight: bold;"> Úsalo con responsabilidad</span></p>
                    <hr class="my-2">
                  <% end%>
                  <h2 class="section-heading mb-4">
                    <span class="section-heading-lower">Guia Virtual |</span>
                    <span class="section-heading-upper">Aprende &amp; Practica</span>
                  </h2>
                  <% if user_signed_in? %>
                    <p class="lead">
                      <%= link_to " Recursos", my_topics_path, class:"btn-means"%>
                    </p>
                  <% else %>
                    <p class="lead">
                      <%= link_to "Iniciar Sesión",  new_user_session_path, class:"btn btn-sm btn-success"%>
                    </p>
                  <% end %>
                </div>
                
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
</section>

app/views/home/welcome.html.erb
<section class="section-welcome">
  <body class="welcome">
    <div id="portada-movil">
      <header>
        <p style="text-align: center">
          <img src="/cover-sm.png" class="img-movil" alt="Portada Guis virtual" width="320" height="auto" />
        </p>
      </header>     
      <div class="col-xl-9 col-lg-10 mx-auto">
        <div class="bg-faded rounded p-3 ">
          <div class="">
            <h1 class="display-5">Hola <%= current_user.name %>!</h1>
            <p class="lead">Bienvenido a tu espacio de aprendizaje online, Espero aprendas mucho, y pongas en practica esos conocimientos</p>
            <hr class="my-2">
            <h2 class="section-heading mb-2">
              <span class="section-heading-lower">Guia Virtual |</span>
              <span class="section-heading-upper">Aprende &amp; Practica</span>
            </h2>
            <p class="lead">
              <%= link_to " Recursos", my_topics_path, class:"btn btn-sm btn-success"%>
            </p>
          </div>
        </div>
      </div>
    </div>
    <section id="no-info-home" class="page-section about-heading">
      <div class="container">
        <div class="about-heading-content">
          <div class="row">
            <div class="col-xl-9 col-lg-10 mx-auto">
              <div class="bg-faded rounded p-3 ">
                <div class="">
                  <h1 class="display-5">Hola <%= current_user.name %>!</h1>
                  <p class="lead">Bienvenido a tu espacio de aprendizaje online, Espero aprendas mucho, y pongas en practica esos conocimientos</p>
                  <hr class="my-2">
                  <h2 class="section-heading mb-4">
                    <span class="section-heading-lower">Guia Virtual |</span>
                    <span class="section-heading-upper">Aprende &amp; Practica</span>
                  </h2>
                  <p class="lead">
                    <%= link_to " Recursos", my_topics_path, class:"btn btn-sm btn-success"%>
                  </p>
                </div>
                <img class="cover-lg" src="/cover-lg.png" alt="Cover index">
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
</section>

app/views/layouts/_header.html.erb
<nav class="left">
  <div class="item menu">
      <i class="fas fa-fw fa-bars nav-icon"></i>Menú
  </div>
  
  <div class="item">
    <%= link_to root_path do %> 
      <img src="/logo.jpg" alt="Logo" class="img-logo rounded-circle text-white"><span class="name-logo">Learning Guide</span>
    <% end %>
  </div>
  
  <hr class="divider">
  <% if user_signed_in? %>

    <div class="item">
        <i class="far fa-list-alt nav-icon"></i> <%= link_to "Categorias", my_categories_path, class: "text-white" %>
    </div>
    
    <div class="item">
        <i class="fas fa-plus-square nav-icon"></i> <%= link_to 'Crear Categoria', new_category_path, class: "text-white" %>
    </div>

    <hr class="divider">

    <div class="item">
        <i class="fab fa-leanpub nav-icon"></i> <%= link_to "Recursos", my_topics_path, class: "text-white" %>
    </div>
    
    <div class="item">
        <i class="fas fa-edit nav-icon"></i> <%= link_to 'Crear recurso', new_topic_path, class: "text-white" %>
    </div>

    <hr class="divider">

    <div class="item">
        <i class="fas fa-book nav-icon"></i> <%= link_to "Agenda", my_schedules_path, class: "text-white" %>
    </div>
    
    <div class="item">
        <i class="fas fa-edit nav-icon"></i> <%= link_to 'Crear agenda', new_schedule_path, class: "text-white" %>
    </div>

    <hr class="divider">

    <div class="item">
      <i class="fas fa-headphones nav-icon"></i><a class="text-white" target="_blanck" href="https://soundcloud.com/discover">Oir música</a>
    </div>
    
    <div class="item">
      <i class="fas fa-sign-out-alt nav-icon"></i> <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "text-white" %>
    </div>

  <% else %>
  <!--  <div class="item afiliarse">
      <i class="fas fa-handshake nav-icon"></i> <a href="https://web.sportplusapp.com/afiliarse/" class="text-white" target="_blank">Afiliarse</a> 
    </div>-->

    <div class="item active">
      <!--<i class="fas fa-check-square nav-icon"></i><%# link_to "Registrarse",  new_user_registration_path, class: "text-white" %>-->
    </div>

    <div class="item active">
      <i class="fas fa-sign-in-alt nav-icon"></i><%= link_to "Iniciar Sesión",  new_user_session_path, class: "text-white" %>
    </div>
  <% end%>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link  rel="icon"   href="/logo-elearning-guide.png" type="image/png" />
    <title>Elearning Guide</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="app/assets/stylesheets/application.css" rel="stylesheets">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet"/>
  </head>
  <body>
    <% if notice %>
      <p class="alert alert-success col-md-3 col-md-offset-4 text-center mx-auto"role="alert" style="font-size: 12px; padding: 7px; width: 300px;"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger col-md-3 col-md-offset-4 text-center mx-auto"role="alert" style="font-size: 12px; padding: 7px; width: 300px;"><%= alert %></p>
    <% end %>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/schedules/_form.html.erb
<section class="section-form">
  <div class="card card-form">
    <div class="card-body">
      <%= form_with(model: @schedule) do |f| %>
      <% if @schedule.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this topic from being saved:</h2>
          <ul>
            <% @schedule.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :Fecha %>
        <%= f.date_field :date,class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :Evento %>
        <%= f.text_field :event,class: 'form-control' %>
      </div>

      <div class="form-group mt-2">
        <%= f.label :Nota %>
        <%= f.rich_text_area :note,class: 'form-control' %>
      </div>

      <div>
        <%= f.submit "Guardar", class:"btn btn-success mt-3" %>
      </div>

    <% end %>
      
    </div>
  </div>
</section>

app/views/schedules/edit.html.erb
<h1>Editar Evento</h1>

<%= render 'form', schedule: @schedule %>


<%= link_to 'Atras', @schedule, class: "btn btn-primary text-white my-2" %>

app/views/schedules/new.html.erb
<h1>Nuevo Evento</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Atras', my_schedules_path, class: "btn btn-primary mt-3" %>

app/views/schedules/show.html.erb
<div class="container contenedor">
  <div id="card-border" class="card" style="width: 36rem;">
    <div id="header-card-color" class="card-header">
      <h5 class="card-title"><%= I18n.l(@schedule.date, format: '%A, %d de %B de %Y') %></h5>
    </div>
    <div class="card-body">
      <h5 class="card-subtitle mb-2 text-muted"><%= @schedule.event %></h5>
      <p class="card-text"><%= @schedule.note %></p>
      <div class="mt-3 content-btns">
        <%= link_to "Atras", my_schedules_path, class: 'btn btn-primary text-white btns' %>
        <%= link_to 'Crear evento', new_schedule_path, class: "btn btn-success text-white btns" %>
        <%= link_to "Editar", edit_schedule_path(@schedule), class: 'btn btn-warning text-white btns' %>
        <%= link_to "Eliminar", @schedule, method: :delete, class: 'btn btn-danger text-white btns' %>
      </div>
    </div>
  </div>
</div>

app/views/topics/_form.html.erb
<section class="section-form">
  <div class="card card-form">
    <div class="card-body">
      <%= form_with(model: @topic) do |f| %>
      <% if @topic.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>
          <ul>
            <% @topic.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :nombre %>
        <%= f.text_field :name,class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :descripción %>
        <%= f.text_field :description,class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :link %>
        <%= f.text_field :link,class: 'form-control' %>
      </div>

      <div class="form-row">
        <div class="form-group col-md-12">
          <label>categorias</label><br>
          <div class="text-dark">
            <%= f.select :category_ids, options_from_collection_for_select(current_user.categories, :id, :name, @topic.categories.pluck(:id)), {}, multiple: true, id: "category_ids", class: "form-control"%>
          </div>
        </div>
      </div>
      <div class="form-group mt-2">
        <%= f.label :nota %>
        <%= f.rich_text_area :note,class: 'form-control' %>
      </div>

      <div>
        <%= f.submit "Guardar", class:"btn btn-success mt-3" %>
      </div>

    <% end %>
      
    </div>
  </div>
</section>

app/views/topics/edit.html.erb
<h1>Editar Recurso</h1>
<%= render "form" %>

app/views/topics/index.html.erb
<h1>Lista de recursos</h1>

<div class="table-responsive">
  <table class="table ">
    <thead class="bg-primary text-white">
      <tr>
        <th scope="col">Nombre </th>
        <th scope="col">Descripción</th>
        <th scope="col">Categoría</th>
        <th scope="col">Ver</th>
      </tr>
    </thead>
    <% @topics.each do |topic| %>
      <tbody class="">
        <tr>
          <th scope="row"><%= topic.name %></th>
          <td><%= topic.description %></td>
          <td><%= topic.user.name %></td>
          <td><%= link_to "Ver más", topic, class:"btn btn-small btn-success"%></td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>

app/views/topics/new.html.erb
<h1 class="title">Agregar Recurso de Aprendizaje</h1>

<%= render "form" %>

app/views/topics/show.html.erb
  <h1 class="title">Nuevo recurso</h1>
  <div class="row">
    <div class="card card-source">
      <div class="card-body card-body-source">
        <h5 class="card-title"><%= @topic.name %></h5>
        <p class="card-text"><%= @topic.description %></p>
        <div class="panel-body well" >
          <h5 class="card-title">Categorías</h5>
          <ul>
            <% @topic.categories.each do |category|%>
              <li style="color: <%= category.color%>"><span style="color: <%= category.color%>" class="pill"><%= category.name %></span></li> 
            <% end %>
          </ul>
        </div>
      </div>
      <hr>
      <div class="toggle">
        <details class="mx-3">
          <summary>Ver Notas</summary>
          <div class="card-body card-body-source texto">
            <small class="text-secondary color-red">Fecha de creación: <%= I18n.l(@topic.created_at,format: "%d / %m / %Y") %></small>
            
            <p class="card-text texto"><%= @topic.note %></p>
            <small class="text-secondary color-red">Última actualizacion: <%= I18n.l(@topic.updated_at,format: "%d / %m / %Y") %></small>
          </div>
        </details>
      </div> 
      <div class="m-3 content-btn-source">
        <a href="<%= @topic.link %>" target="_blanck" class="btn btn-primary btn-small btn-source">Ir al Recurso</a>
      </div>
    </div>
  </div>
  <div class="mt-3 content-btns">
 
    <%= link_to 'Editar', edit_topic_path(@topic), class: 'btn btn-warning text-white btns' %>
    <%= link_to 'Atras', my_topics_path, class: 'btn btn-primary text-white btns' %>
    <%= link_to "Eliminar", @topic, method: :delete, class: 'btn btn-danger text-white btns' %>
    
  </div>

app/views/users/my_categories.html.erb
<h1 class="title">Categorías</h1>
<section class="section-categories">
  <div class="row">
    <% @categories.each do |category| %>
    <div class="col-sm-3">
      <div id="card-border" class="card mt-4">
        <div class="card-header" style="background-color: <%= category.color%>">
          <h5 class="card-title text-white"><%= category.name %></h5>
        </div>
        <div class="card-body card-categories">
          <p>Ref. <%= category.id %></p>
          <%= link_to "Más", category, class:"btn btn-sm btn-success"%>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div class="row row-pagy">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</section>

app/views/users/my_schedules.html.erb
<h1 class="title">Agenda</h1>
<section class="section-categories">
  <div class="row">
    <% @schedules.each do |schedule| %>
    <div class="col-sm-3 my-2">
      <div id="card-border" class="card mt-2">
        <div id="header-card-color" class="card-header text-white h5" >
          <%= I18n.l(schedule.date, format: '%A, %d de %B de %Y') %>
        </div>
        <div class="card-header ">
          <p class="h6"><%= schedule.event%></p>
        </div>
        <div>
          <details class="mx-3">
            <summary>Ver Notas</summary>
              <p class="card-text"><%= schedule.note %></p>
          </details>
        </div> 
        <div class="d-grid gap-2 card-footer">
          <%= link_to "Ver evento", schedule, id:"btn", class:"btn btn-sm btn-success"%>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div class="row row-pagy">
    
  </div>
</section>